### ISSUE TITLE
Soil

### ISSUE THREAD

**Issue by retlehs** [globalis-ms/wp-cubi#42]
could you please remove [soil](https://roots.io/plugins/soil/) from this project? it's a premium plugin

**Comment by pierre-dargham** [comment]
Hello @retlehs !

I'm a little confused by your demand here. I was aware that you (roots) were selling something with soil on [roots.io](https://roots.io/) but I thought that soil was an open-source software, and that you selling it was either some sort of premium support service, or a way to invite users to help you financially, which is totally legit, because it's a great piece of software and I know support / maintenance of such project does cost a lot of time.

So after you opened this issue, I went on soil github repository to double-check which license is used, and it was a relief to see it's distributed with an MIT license, as indicated on both [LICENSE.md](https://github.com/roots/soil/blob/master/LICENSE.md) and [soil.php](https://github.com/roots/soil/blob/master/soil.php#L10) . That seems logical, because you promote a collaborative approach, and the code history now contains commits from 35 developers from many different organizations (including me ;) even if it was one very small bugfix).

Could you please be more specific about the problem of having soil as a composer dependency of wp-cubi ? I think that we do not break any rule of the MIT license here, and we'll truly correct things if I'm wrong.

We are big fans of your contributions to the WordPress ecosystem, and having dependencies on some of your packages seemed also a way to acknowledge the quality of your work.

Hope we wan discuss it further,

Bests regards,
Pierre

**Comment by pierre-dargham** [comment]
I honestly think, despite the note in your README, that what really encourages the use of soil without paying for it, is its availability on your github and packagist official pages. That's what creates confusion, not a few minor projects having it as a dependency. 

Actually, you could have it under an open-source license without distributing the code for free. If you want people to pay for it, make your checkout page the only way you distribute it, it would avoid any confusion. You could make your github repository private, and setup a private composer repository that handles license keys like [some are doing with their premium plugins](https://deliciousbrains.com/composer-premium-wordpress-plugins/). Another example : ACF-PRO is released under GPLv2 license, but it's not available for free on ACF official github, or any other official page of their own, so there is no confusion about it.

Plus, having it as a public repository to collect contributions from the community, but asking the community not to use it for free seems a little inconsistent. It really sends a negative message to developers about your motivations, like "yeah, help me to maintain the plugin, but don't use it without paying". I totally understand that you want to make money with it, but again, when you make an open-source software, publicly available on github, you should accept the very basic rules of the game : people can contribute to my plugin, but they can also use it and redistribute it.

However, our goal here is not to bother you, or to make you lose money, if that's what you're feeling. If the mention of soil being distributed for free is your issue, would you be more happy if we make a fork of it ? So, instead of telling people that they will have `roots/soil` for free when they install wp-cubi, we'll be telling them that they will have `globalis/wp-dom-cleaner` (or something like that).

**Comment by retlehs** [comment]
i'm not here to discuss our business model with you (you're aware that there are several large plugin shops that do this, right?) - i came here to nicely ask that you don't include our commercial plugin as part of your default dependencies. your response is clear and your ethics are wack. make a fork of our paid plugin? shrug.
